version: '3.6'
services:
  server:
    image: jekyll/jekyll:3.8
    volumes:
      - "$PWD:/srv/jekyll"
      - "$PWD/bundle:/usr/local/bundle"
    ports:
      - "4000:4000" # server port
      - "35729:35729" # livereload port
    command:
      - bundle
      - exec
      - jekyll
      - serve
      - --incremental
      - --watch
      - --livereload
      - --host
      - "0.0.0.0"
      - --port
      - "4000"
